import os

def validate_vcf_file(vcf_path: str) -> str:
    """
    Validates that the VCF file generated by the GATK HaplotypeCaller 
    pipeline exists and is readable.
    """
    if not os.path.exists(vcf_path):
        raise FileNotFoundError(f"Genomic pipeline failed to produce VCF at: {vcf_path}")
    
    if not vcf_path.lower().endswith('.vcf'):
        raise ValueError(f"Invalid file format. Expected GATK output (.vcf): {vcf_path}")
    
    # Check if the file is empty (GATK sometimes produces empty VCFs if no variants found)
    if os.path.getsize(vcf_path) == 0:
        raise ValueError(f"The generated VCF file is empty. No variants were called.")

    print(f" GATK Output Validated: {vcf_path}")
    return vcf_path
